In [2]:
import torch 

In [6]:
t = torch.randn(4, 4)
t

tensor([[ 0.9248, -1.3997,  1.1693,  0.3116],
        [-0.0704,  2.0453,  0.0448,  0.9771],
        [ 1.0255, -0.3370, -0.8706, -1.0842],
        [ 0.8954, -1.0748,  1.2585,  1.2315]])

In [14]:
x_max = t.max(1)[0]
print(x_max)
t - x_max[:, None]

tensor([1.1693, 2.0453, 1.0255, 1.2585])


tensor([[-0.2445, -2.5690,  0.0000, -0.8577],
        [-2.1157,  0.0000, -2.0005, -1.0682],
        [ 0.0000, -1.3625, -1.8962, -2.1097],
        [-0.3631, -2.3333,  0.0000, -0.0270]])